openapi: 3.0.1
info:
  title: CalculatorAPI
  description: API Definition of CalculatorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/calculator
paths:
  /:
    post:
      responses:
        default:
          description: Default response
  /add:
    get:
      responses:
        default:
          description: Default response
